name: exoheal
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  sqflite: ^2.0.0+4
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.1
  feather_icons: ^1.1.0-nullsafety.0
  flutter_svg: ^0.22.0
  get: ^4.3.8
  path_provider: ^2.0.3
  firebase_auth: ^3.2.0
  email_validator: ^2.0.1
  fl_chart: ^0.41.0
  azblob: ^2.0.0
  sleek_circular_slider: ^2.0.1
  image_picker: ^0.8.4+5
  mime: ^1.0.1
  rive: ^0.8.4
  audio_video_progress_bar: ^0.10.0
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/exohealhands.svg
    - assets/images/Desk_duotone_line.svg
    - assets/images/Arhive_light.svg
    - assets/images/Sort.svg
    - assets/images/Group 24.svg
    - assets/images/Group 26.jpg
    - assets/images/Group 28.svg
    - assets/images/robotichandhome.svg
    - assets/images/dualhandhome.svg
    - assets/images/separation.svg
    - assets/images/No task empty state.svg
    - assets/animations/allexohealexercises.riv
    - assets/images/handdone.svg
    - assets/images/handdonewithsensations.svg
    - assets/animations/mirrortherapyidle.riv
    - assets/animations/colorizedriveanim.riv
    - assets/animations/fixedriveanim.riv
    # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: GilroyBold
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
    - family: GilroySemiBold
      fonts:
        - asset: fonts/FontsFree-Net-gilory.ttf
    - family: GilroyMedium
      fonts:
        - asset: fonts/Gilroy-Medium.ttf
    - family: ProximaNovaSemiBold
      fonts:
        - asset: fonts/FontsFree-Net-Proxima-Nova-Sbold.otf
    - family: ProximaNovaRegular
      fonts:
        - asset: fonts/Proxima Nova Font.otf
    - family: Interregular
      fonts:
        - asset: fonts/Inter-Regular.ttf
    - family: Intermedium
      fonts:
        - asset: fonts/Inter-Medium.ttf
    - family: Intersemibold
      fonts:
        - asset: fonts/Inter-SemiBold.ttf
      # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
